# Default Retry Strategy Library
---
strategyMappings:
- regexes:
  - "status code: 4\\d\\d"
  strategy: !<Fatal> {}
- regexes:
  - "simple"
  strategy: !<Regular>
    maxAttempts: 5
    intervalMillis: 100
defaultRetryStrategy: !<Exponential>
  maxAttempts: 5
  initialIntervalMillis: 20
  multiplier: 1.5
